### ISSUE TITLE
RhythmBeats! Game: "Invalid URL '': No schema supplied. Perhaps you meant http://?"

### ISSUE THREAD

**Issue by CharlieFuu69** [CharlieFuu69/RenPy_RhythmBeats#3]
En las últimas horas, algunos testers me han comunicado del un incidente al realizar la descarga de recursos de **Ren'Py RhythmBeats! Game**:

![Captura de pantalla (549)](https://user-images.githubusercontent.com/77955772/221025765-f9cde828-d701-4a5c-b000-2971e12c33ac.png)

### Detalles:
El error `Invalid URL '': No schema supplied. Perhaps you meant http://?` impide realizar las descargas de recursos para comenzar a jugar.

> **[Actualización - 17:45 GMT -3]:**
> El error ha sido encontrado. Ha sido provocado por un cambio en los endpoints de Mediafire. El error no es causado por el juego, por el contrario, el juego no sabe manipular el nuevo formato aplicado en Mediafire.
> Se está intentando solucionar el problema. Probablemente necesite compilar una nueva actualización global, posterior a haber solucionado el problema.

> **[Actualización - 01:05 GMT -3]:** 
> Mediafire parece que agregó una verificación de Cloudflare, lo que ocasiona que falle la recuperación de URLs de descarga de los recursos. Por alguna razón el código funciona en mi terminal y recupera las URLs de descarga, pero en Ren'Py no puedo saltarme la verificación de Cloudflare.
> No sé por qué carajos funciona así, y parece que esto me tomará un tiempo. Si no encuentro más alternativas, tendré que migrar los activos del juego hacia Anonfiles y decirle adiós a Mediafire.

> **[Actualización - 03:25 GMT -3]:**
> Creo que ya me estoy rindiendo. Parece que tendré que utilizar a Anonfiles como host de los recursos del juego.
> Si alguien conoce un servicio gratuito de almacenamiento que se pueda raspar URLs de descargas mediante el HTML, bienvenido sea. Anonfiles funciona, pero no sé si será muy confiable para almacenar los recursos del juego.

> **[Actualización - 18:57 GMT -3]:**
> Almacenaré los paquetes del juego aquí en GitHub. Es una alternativa a Mediafire para albergar los Assets.
> Comenzaré a modificar el código para modificar los endpoints de descarga.

---

### Status del incidente:
> - [x] **Reporte recibido: `Invalid URL '': No schema supplied. Perhaps you meant http://?`.**
> - [x] **Incidente bajo investigación.**
> - [x] **Supervisando el error...**
> - [x] **Problema identificado: Verificador de Cloudflare.**
> - [x] **Alternativa encontrada: Hostear los recursos en GitHub.**
> - [x] **Corrección de errores en actualización.**
> - [x] **Actualización `v1.02.1b` emitida. Ver **[notas de actualización](https://github.com/CharlieFuu69/RenPy_RhythmBeats/releases/tag/v1.02.1b_global)****

**Comment by Andredron** [comment]
Puedo decir que es trivial, pero por qué no hacer una versión independiente durante un tiempo que se actualice como renpy, sólo que al pulsar el botón de actualizar, se active el módulo de actualización y salga un error. Sí es una muletilla, pero de momento una solución mientras se arregla el error. Aún así es mejor que un proyecto completamente muerto

I can say it's trivial, but why not make a standalone version for a while that updates as renpy, only when you press the update button, the update module kicks in, and the error pops up. Yes it's a crutch, but for the time being a solution while the error is fixed. Still looks better than a completely dead project

![image](https://user-images.githubusercontent.com/55322207/221101440-f16fd1fd-f01c-49a7-8b1a-68571eaf4f38.png)

**Comment by CharlieFuu69** [comment]
**[SP]:** Sinceramente, ya estoy considerando la idea de mudar los activos hacia [Anonfiles](https://anonfiles.com/). Al menos ese host no me está dando problemas, pero más cómodo se me hacía usar a Mediafire.

Utilizaría el updater de Ren'Py, pero a diferencia del sistema de descargas que hice, el de Ren'Py no está soportado en Android. (Mira más en el repositorio de [Ren'Py Asset Download Complement](https://github.com/CharlieFuu69/RenPy_Asset_Download_Complement)).

Probablemente mañana o pasado mañana tendré actualizados los nuevos endpoints de descarga. Me he quedado desconcertado con esto =(

---

**[EN]:** Honestly, I am already considering the idea of moving the assets to [Anonfiles](https://anonfiles.com/). At least that host is not giving me problems, but it made me more comfortable using Mediafire.

I would use the Ren'Py updater, but unlike the download system I made, the Ren'Py updater is not supported on Android. (Watch more in [Ren'Py Asset Download Complement](https://github.com/CharlieFuu69/RenPy_Asset_Download_Complement) repository).

Probably tomorrow or the day after tomorrow I will have the new download endpoints updated. I'm baffled by this =(
