### ISSUE TITLE
Still having an issue with the new module

### ISSUE THREAD

**Issue by de-luxe110** [CharlieFuu69/RenPy_RhythmBeats#31]
Thank you so much for the update, however I am still getting an error with just the regular code in the updated documentation. Same as before, I copied it to a tee and cross checked it to make sure it's correct but it still shows this error. Here is the traceback. 

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 79, in script
    python:
  File "game/script.rpy", line 81, in <module>
    my_instance = RhythmPlayground(
RhythmBeatsException: Beatmap read error: TypeError("a bytes-like object is required, not 'str'")

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 79, in script
    python:
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\User\Downloads\renpy-8.0.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 81, in <module>
    my_instance = RhythmPlayground(
  File "game/rbs_plugin_alt.rpym", line 298, in __init__
  File "game/rbs_plugin_alt.rpym", line 340, in load
RhythmBeatsException: Beatmap read error: TypeError("a bytes-like object is required, not 'str'")

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.1.23060707
rhythm test 1.0
Tue Jan  2 18:22:55 2024
```

**Comment by CharlieFuu69** [comment]
Hello!
This error seems to occur when loading the beatmap, and apparently it happens because the code in charge of loading the beatmap expects to receive the `.beat` file as a byte object and not as a `str()` object.
Perhaps this is happening due to an incompatibility with Ren'Py 8, since in these new versions the behavior of several Python functions has slightly changed.

Since I have developed this module on v7.4.11, maybe that is the reason why I haven't gotten that error. Likewise, I'm going to download Ren'Py 8 to test my hypothesis.

---

**Roadmap started at 2024-01-02 at 14:34 UTC**
> - [x] **[`2024-01-02 at 14:34 UTC`] Reported critical error: Problems in `RhythmPlayground().load()` method. Beatmap loading error.**
> - [x] **[`2024-01-02 at 14:34 UTC`] Error under investigation...**
> - [ ] [`N/A`] Investigation finished.
> - [ ] [`N/A`] Fixing source code.
> - [ ] [`N/A`] Investigation finished.
> - [ ] [`N/A`] Testing in local environment...
> - [ ] [`N/A`] Investigation finished.
> - [ ] [`N/A`] Preparing RhythmBeats Kit update...
> - [ ] [`N/A`] Investigation finished.
> - [ ] [`N/A`] Update "RhythmBeats Kit" released as v1.07.1b

**Comment by CharlieFuu69** [comment]
Indeed, this error is only occurring in versions higher than Ren'Py 8. Its execution in Ren'Py v7.4.x is completely clean. I will try to create backward compatibility to mitigate this error.

![image](https://github.com/CharlieFuu69/RenPy_RhythmBeats/assets/77955772/17cdbb9c-7b64-4d34-b782-f4787697005d)

> _**[NOTE]:** Roadmap updated._

**Comment by CharlieFuu69** [comment]
@de-luxe110 Update `v1.07.1b` released

Check the changes and download the new version at **[Release v1.07.0b_module](https://github.com/CharlieFuu69/RenPy_RhythmBeats/releases/tag/v1.07.1b_module)**.

The packages containing the RhythmBeats core and the beatmap creation tools have been separated so you don't have to download everything again. Check the ZIP package named `RhythmBeats_v1.07.1b_rev1.zip`.

> _**[NOTE]:** Roadmap finished. This issue will be marked as closed._
