### ISSUE TITLE
Error durante el reinicio 

### ISSUE THREAD

**Issue by Andredron** [CharlieFuu69/RenPy_RhythmBeats#4]
1) He descargado la nueva versión, tras descargar los recursos aparece la notificación de que es necesario reiniciar la aplicación, al pulsar para confirmar, aparece el siguiente error
![Снимок экрана (52)](https://user-images.githubusercontent.com/55322207/221378908-41273a9c-0741-4fec-ba9e-555a2b15db1b.png)

cerrar la aplicación y volver a iniciarla normalmente inicia

**Comment by Andredron** [comment]
Ejecutar a través de exe no renpy.

**Comment by CharlieFuu69** [comment]
**[SP]:** Bro. Creo que soy realmente estúpido.
He utilizado un parámetro que no existe en la función `renpy.quit()`, así que es completamente un error humano de mi parte.

* **Esto es incorrecto:**
  ```python
  renpy.quit(save=False, restart=True)
  ```

* **Esto es correcto:**
  ```python
  renpy.quit(save=False, relaunch=True)
  ```
Dame unos 15 minutos y vuelve a comprobar el mismo release. Estarán los ejecutables actualizados. Comentaré aquí cuando haya actualizado esos ejecutables defectuosos.

---

**[EN]:** Bro. I think I'm really stupid.
I've used a parameter that doesn't exist in the `renpy.quit()` function, so it's completely human error on my part.

* **This is incorrect:**
  ```python
  renpy.quit(save=False, restart=True)
  ```

* **This is correct:**
  ```python
  renpy.quit(save=False, relaunch=True)
  ```

Give me about 15 minutes and check again the same release. The executables will be updated. I will comment here when I have updated those bad executables.

**Comment by CharlieFuu69** [comment]
**[SP]:** Error solucionado :3
Hasta me había percatado que una de las nuevas características no se había añadido. Descarga nuevamente el EXE desde el **[Release v1.02.1b](https://github.com/CharlieFuu69/RenPy_RhythmBeats/releases/tag/v1.02.1b_global)**

**[EN]:** Bug fixed :3
I had even noticed that one of the new features had not been added. Download the EXE again from the **[Release v1.02.1b](https://github.com/CharlieFuu69/RenPy_RhythmBeats/releases/tag/v1.02.1b_global)**.
