### ISSUE TITLE
Añada las siguientes mejoras

### ISSUE THREAD

**Issue by Andredron** [CharlieFuu69/RenPy_RhythmBeats#5]
Intentaré explicar con mis propias palabras por qué tal o cual actividad debería añadirse a tu tiempo libre.

1) Añade un reproductor de música mientras descargas recursos del juego. Cuando suena la misma melodía, al cabo de un rato resulta molesto. Dar la posibilidad de ajustar el volumen de la música o cambiar las canciones molestas. Cuando descargues los cracks para la app allí y entonces hay un botón para silenciar el sonido completamente)
![image](https://user-images.githubusercontent.com/55322207/221383296-6719a0a8-c02a-486c-85e0-316cce8f10a9.png)

2) Si es posible, no hagas una descarga completa de todo, pero descarga una básica para empezar: 

portadas de discos con información textual

música (demos) que pueda escucharse previamente

Como ejemplo sencillo con una aplicación Deеmo. Allí, todos los proyectos están desglosados por álbumes, puedes escucharlos de antemano y, cuando decides ponerlos, compras (en nuestro caso, descargas) el álbum y lo reproduces. 

Por qué es necesario. Ahorra tráfico de Internet al usuario (por ejemplo, he oído que en algunos países Internet es de pago, en Rusia no hay límite, pagas una vez al mes y puedes descargar 5 terabytes, no tienes que pagar más).

Cuantos más álbumes, más peso tendrá el proyecto, y algunos usuarios no tienen mucho espacio en sus teléfonos.

![image](https://user-images.githubusercontent.com/55322207/221383351-6476baa9-47ba-49af-99e8-92681f5306b9.png)

3) Si se añade el segundo punto, añada también la posibilidad de eliminar los álbumes descargados, con la opción de descargarlos en cualquier momento. Los usuarios de Android respirarán aliviados.

4) Ordena los álbumes de recortes. Tienes una lista creciente de álbumes de música, tiene sentido publicar un montón de música de 1 álbum

![image](https://user-images.githubusercontent.com/55322207/221383615-b7609861-7420-4b37-b8c1-43f12af9b464.png)

Como ejemplo: Hay un álbum https://vgmdb.net/album/44925 en él un montón de canciones, en Rusia hay una comunidad de fans de novedades visuales que coleccionan discos de audio de ellos. https://vk.com/konpeki allí recuerdo incluso un CD de 1998 que no está disponible en internet, sólo en subastas o a través de fans.

Descarga a través del álbum de búsqueda
https://vk.com/konpeki?w=wall-155296193_1831

Y ya es una selección con un estilo bastante decente, además de algunas grabaciones realmente raras, para un fan de las novelas visuales japonesas será un día de fiesta. Además de la información sobre los CD, también puede descargarlos y escucharlos en línea haciendo clic en el icono situado junto al nombre debajo de la cabecera del álbum

5) Hazlo por tu propio placer y no me guardes rencor por no dejarte trabajar tranquilamente en el proyecto)))

![image](https://user-images.githubusercontent.com/55322207/221382903-b2aecd74-ed89-43c3-acab-dfa5400c806e.png)
La chica tiene el cartel - Escribo código abierto por diversión.
Oragutang tiene una persona cualquiera de internet que empezó a usarlo y ahora exige documentación para él.

**Comment by Andredron** [comment]
1) https://lemmasoft.renai.us/forums/viewtopic.php?f=51&t=62120 - como plantilla

**Comment by CharlieFuu69** [comment]
> _**NOTE:** Translation required because images will be inserted. It is recommended to use the "enhancement" tag to request possible features or additions_

Hmmm, algunas de las características que mencionas, han sido añadidas al juego demostrativo de **"Ren'Py RhythmBeats!"**, pero abordaré cada uno de los puntos que me has señalado.

> _"Hazlo por tu propio placer y no me guardes rencor por no dejarte trabajar tranquilamente en el proyecto"_

Tranquilo. Si la gente solicita nuevas características, veré en la medida de lo posible si puedo agregarlas o no al juego =D

> _**ACLARATORIA PERSONAL ANTES DE EMPEZAR:** Este juego, solo es un juego demostrativo, pues el objetivo principal de este proyecto es de que algunos desarrolladores/programadores puedan integrar un sistema de acción rítmica en una novela visual hecha con Ren'Py. Por su parte, **"Ren'Py RhythmBeats! Game"** solo es una demostración de lo que se podría hacer. La creatividad, siempre quedará a decisión del usuario final de este proyecto, como programador._
> _No puedo negar eso si, que a este juego le tengo bastante cariño, sobre todo porque soy un fan ávido de los juegos rítmicos._

---

Ahora si, empecemos:

* **Añade un reproductor de música mientras descargas recursos del juego:**
  Esta solicitud es un poco complicada, porque lamentablemente Ren'Py no es un motor que sea completamente eficiente al hacer demasiadas cosas, mucho menos en actividades de I/O como las descargas de recursos.
  Si bien, podría agregar unas cuantas pistas musicales para reproducir durante la descarga y colocarlas en cola para reproducirlas secuencialmente durante la descarga, agregar más elementos en la UI durante la descarga no va a ser tan benéfico.

  Por supuesto, asumo que estar escuchando la misma canción una y otra vez, puede ser agotador. Por esta misma razón, consideraré esta idea parcialmente, probablemente a mediano plazo :3

* **Si es posible, no hagas una descarga completa de todo, pero descarga una básica para empezar:**
  Si, de hecho esto lo había pensado hace un tiempo. Tenía pensado hacer que antes de la primera descarga fuera posible seleccionar entre una "Descarga Ligera" (solo canciones con sus respectivos beatmaps y metadatos), y una "Descarga Completa" (canciones + 2DMV).
  De aplicarlo ahora mismo va a ser un poco dificil ya que estoy constantemente mejorando de forma interna el sistema rítmico, pero es una característica que si he considerado =D

* **Música (demos) que pueda escucharse previamente:**
  Esta característica se añadió hace unas 3 o 4 actualizaciones atrás. En tanto ingresas al menú de pistas, es posible oir una prevista de la canción antes de jugarla (como en casi todos los juegos rítmicos que existen hoy en día).

* **Añada también la posibilidad de eliminar los álbumes descargados, con la opción de descargarlos en cualquier momento. Los usuarios de Android respirarán aliviados:**
  Esto era parte de mi plan de realizar "Descargas Ligeras" o "Descargas Completas", asi que si, también lo estoy considerando, pero por el momento mi prioridad es mejorar el sistema de acción rítmica.

* **Ordena los álbumes de recortes. Tienes una lista creciente de álbumes de música, tiene sentido publicar un montón de música de 1 álbum:**
  En el caso actual de **"Ren'Py RhythmBeats! Game"**, puedes filtrar la lista de canciones desde el menú contextual "Filtro" en la parte superior del menú de pistas:
  ![image](https://user-images.githubusercontent.com/77955772/221384572-f941bad2-1acf-48fc-bc38-7020516f4529.png)

  En este caso, se ordenan por franquicia (creo que se nota que soy muy fan de "Love Live!" y "Project SEKAI" haha).
  Si este filtro ha sido configurado en **"Todos"**, se verán todas las canciones que se añadieron al juego, mientras que si se selecciona otra categoría, este solo mostrará las canciones de cierta franquicia, o canciones extras añadidas.

* **[https://lemmasoft.renai.us/forums/viewtopic.php?f=51&t=62120](https://lemmasoft.renai.us/forums/viewtopic.php?f=51&t=62120) - como plantilla:**
  Hmm, no sé si será necesario para el juego rítmico agregar una Music Room, aunque ya lo he hecho en otros proyectos:
  ![image](https://user-images.githubusercontent.com/77955772/221385290-28033b70-e73e-4d01-bfc9-be2e553044e9.png)

  Apegándome a mi aclaratoria personal del inicio, creo que agregar una Music Room en una VN dependerá netamente si el desarrollador de cierta novela visual quiere agregarla en su juego. En el caso de este juego demostrativo, no creo que sea tan necesario (o podría considerarlo).

---

De lo que me dijiste en el punto 5, mantén la calma. A veces ando ocupado, pero por el cariño que le tengo a este proyecto, seguro que haré caso a alguna de tus sugerencias y a las sugerencias de otros testers =D

Si tienes alguna otra inquietud, ¡no dudes en manifestarlo en esta sección del repositorio!
Todo comentario será bienvenido, sobre todo si se trata reporte de errores XD.
